Description: Create App Env

Parameters:
  NetworkStackName:
    Type: String
    Default: Network
  S3BucketStackName:
    Type: String
    Default: s3-lambda-data-receiver
  DynamoDBStackName:
    Type: String
    Default: dynamodb-lambda-data-receiver
  EnvironmentName:
    Type: String
    Default: production
  OwnerTeam:
    Type: String
    Default: development
  Project:
    Type: String
    Default: https://github.com/allanmoraes/lambda-data-receiver
  S3Key:
    Type: String
  LambdaFunctionName:
    Type: String
    Default: lambda-data-receiver
  LambdaSecurityGroupName:
    Type: String
    Default: lambda-data-receiver-sg
  LambdaExecutionRoleName:
    Type: String
    Default: lambda-data-receiver-role

Resources:
  LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: !Sub ${EnvironmentName}-${LambdaFunctionName}
        Handler: lambda_function.lambda_handler
        Role: !GetAtt LambdaExecutionRole.Arn 
        Runtime: python3.11
        Code: 
          S3Bucket:
            Fn::ImportValue:
                  Fn::Sub: "${S3BucketStackName}-S3BucketAppName"
          S3Key: !Sub ${S3Key}
        Environment:
          Variables:
            DYNAMODB_TABLE_NAME:
               Fn::ImportValue:
                  Fn::Sub: "${DynamoDBStackName}-DataReceiverDynamoDBTableName"
        Timeout: 30
        MemorySize: 256

        Tags:
          - Key: Name
            Value: !Sub ${EnvironmentName}-${LambdaFunctionName}
          - Key: managedby
            Value: cloudformation
          - Key: owner-team
            Value: !Sub ${OwnerTeam}
          - Key: project
            Value: !Sub ${Project}
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref LambdaExecutionRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LogsWritePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
        - PolicyName: S3RWPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:PutObject'
                Resource:
                  - Fn::ImportValue:
                      Fn::Sub: "${S3BucketStackName}-S3BucketAppArn"
                  - Fn::ImportValue:
                      Fn::Sub: "${S3BucketStackName}-S3BucketExportArn"
        - PolicyName: DynamoDBRWPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:BatchGetItem'
                  - 'dynamodb:BatchWriteItem'
                  - 'dynamodb:PutItem' 
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:Scan'
                  - 'dynamodb:Query'
                  - 'dynamodb:UpdateItem'
                Resource:
                  - Fn::ImportValue:
                      Fn::Sub: "${DynamoDBStackName}-DataReceiverDynamoDBTableARN"
      Tags:
        - Key: managedby
          Value: cloudformation
        - Key: owner-team
          Value: !Sub ${OwnerTeam}
        - Key: project
          Value: !Sub ${Project}

Outputs:
  LambdaFunctionName:
    Description: 'ARN da Lambda Function'
    Value: !Ref LambdaFunction
    Export:
      Name: "lambda-data-receiver-LambdaFunctionName"

  LambdaFunctionArn:
    Description: 'ARN da Lambda Function'
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: "lambda-data-receiver-LambdaFunctionArn"